#pragma once
#include "Move.h"

class Character {
public:
	void UpdateCharacter(bool left, bool right, bool down, bool up, bool jump, bool light, bool heavy, bool special, int stageX0, int stageY0, int stageX1, int stageY1);
	bool IsAlive(int stageWidth, int stageHeight, int leniancy);
	bool MoveDraw(int move);
	bool IsMoveColliding(int Player2x, int Player2y, int Player2width, int Player2height);
	int MoveX0(int move);
	int MoveY0(int move);
	int MoveX1(int move);
	int MoveY1(int move);
	int MoveThatHitStun();
	int MoveThatHitDamage();
	int MoveThatHitScalarX();
	int MoveThatHitScalarY();
	int MoveThatHitFixedX();
	int MoveThatHitFixedY();
	void Initialise(int xReferral, int yReferral, int livesReferral, int widthReferral, int heightReferral, float walkSpeedReferral, float aerialSpeedReferral, float aerialAccelerationReferral, float walkAccelerationReferral, float groundJumpHeightReferral, float aerialJumpHeightReferral, float fallAccelerationReferral, float fallSpeedReferral, float weightReferral, int maxDoubleJumpReferral, int forwardLightAdditionalXReferral, int forwardLightAdditionalYReferral, int forwardLightWidthReferral, int forwardLightHeightReferral, float forwardLightStunDurationReferral, float forwardLightScalarXReferral, float forwardLightScalarYReferral, float forwardLightFixedXReferral, float forwardLightFixedYReferral, float forwardLightVxReferral, float forwardLightVyReferral, float forwardLightDamageReferral, float forwardLightStartUpDurationReferral, float forwardLightActiveDurationReferral, float forwardLightEndLagDurationReferral, bool forwardLightIsAttachedToPlayerReferral, bool forwardLightDissapearOnHitReferral, int upLightAdditionalXReferral, int upLightAdditionalYReferral, int upLightWidthReferral, int upLightHeightReferral, float upLightStunDurationReferral, float upLightScalarXReferral, float upLightScalarYReferral, float upLightFixedXReferral, float upLightFixedYReferral, float upLightVxReferral, float upLightVyReferral, float upLightDamageReferral, float upLightStartUpDurationReferral, float upLightActiveDurationReferral, float upLightEndLagDurationReferral, bool upLightIsAttachedToPlayerReferral, bool upLightDissapearOnHitReferral, int downLightAdditionalXReferral, int downLightAdditionalYReferral, int downLightWidthReferral, int downLightHeightReferral, float downLightStunDurationReferral, float downLightScalarXReferral, float downLightScalarYReferral, float downLightFixedXReferral, float downLightFixedYReferral, float downLightVxReferral, float downLightVyReferral, float downLightDamageReferral, float downLightStartUpDurationReferral, float downLightActiveDurationReferral, float downLightEndLagDurationReferral, bool downLightIsAttachedToPlayerReferral, bool downLightDissapearOnHitReferral, int forwardHeavyAdditionalXReferral, int forwardHeavyAdditionalYReferral, int forwardHeavyWidthReferral, int forwardHeavyHeightReferral, float forwardHeavyStunDurationReferral, float forwardHeavyScalarXReferral, float forwardHeavyScalarYReferral, float forwardHeavyFixedXReferral, float forwardHeavyFixedYReferral, float forwardHeavyVxReferral, float forwardHeavyVyReferral, float forwardHeavyDamageReferral, float forwardHeavyStartUpDurationReferral, float forwardHeavyActiveDurationReferral, float forwardHeavyEndLagDurationReferral, bool forwardHeavyIsAttachedToPlayerReferral, bool forwardHeavyDissapearOnHitReferral, int upHeavyAdditionalXReferral, int upHeavyAdditionalYReferral, int upHeavyWidthReferral, int upHeavyHeightReferral, float upHeavyStunDurationReferral, float upHeavyScalarXReferral, float upHeavyScalarYReferral, float upHeavyFixedXReferral, float upHeavyFixedYReferral, float upHeavyVxReferral, float upHeavyVyReferral, float upHeavyDamageReferral, float upHeavyStartUpDurationReferral, float upHeavyActiveDurationReferral, float upHeavyEndLagDurationReferral, bool upHeavyIsAttachedToPlayerReferral, bool upHeavyDissapearOnHitReferral, int downHeavyAdditionalXReferral, int downHeavyAdditionalYReferral, int downHeavyWidthReferral, int downHeavyHeightReferral, float downHeavyStunDurationReferral, float downHeavyScalarXReferral, float downHeavyScalarYReferral, float downHeavyFixedXReferral, float downHeavyFixedYReferral, float downHeavyVxReferral, float downHeavyVyReferral, float downHeavyDamageReferral, float downHeavyStartUpDurationReferral, float downHeavyActiveDurationReferral, float downHeavyEndLagDurationReferral, bool downHeavyIsAttachedToPlayerReferral, bool downHeavyDissapearOnHitReferral, int forwardAerialAdditionalXReferral, int forwardAerialAdditionalYReferral, int forwardAerialWidthReferral, int forwardAerialHeightReferral, float forwardAerialStunDurationReferral, float forwardAerialScalarXReferral, float forwardAerialScalarYReferral, float forwardAerialFixedXReferral, float forwardAerialFixedYReferral, float forwardAerialVxReferral, float forwardAerialVyReferral, float forwardAerialDamageReferral, float forwardAerialStartUpDurationReferral, float forwardAerialActiveDurationReferral, float forwardAerialEndLagDurationReferral, bool forwardAerialIsAttachedToPlayerReferral, bool forwardAerialDissapearOnHitReferral, int backAerialAdditionalXReferral, int backAerialAdditionalYReferral, int backAerialWidthReferral, int backAerialHeightReferral, float backAerialStunDurationReferral, float backAerialScalarXReferral, float backAerialScalarYReferral, float backAerialFixedXReferral, float backAerialFixedYReferral, float backAerialVxReferral, float backAerialVyReferral, float backAerialDamageReferral, float backAerialStartUpDurationReferral, float backAerialActiveDurationReferral, float backAerialEndLagDurationReferral, bool backAerialIsAttachedToPlayerReferral, bool backAerialDissapearOnHitReferral, int upAerialAdditionalXReferral, int upAerialAdditionalYReferral, int upAerialWidthReferral, int upAerialHeightReferral, float upAerialStunDurationReferral, float upAerialScalarXReferral, float upAerialScalarYReferral, float upAerialFixedXReferral, float upAerialFixedYReferral, float upAerialVxReferral, float upAerialVyReferral, float upAerialDamageReferral, float upAerialStartUpDurationReferral, float upAerialActiveDurationReferral, float upAerialEndLagDurationReferral, bool upAerialIsAttachedToPlayerReferral, bool upAerialDissapearOnHitReferral, int downAerialAdditionalXReferral, int downAerialAdditionalYReferral, int downAerialWidthReferral, int downAerialHeightReferral, float downAerialStunDurationReferral, float downAerialScalarXReferral, float downAerialScalarYReferral, float downAerialFixedXReferral, float downAerialFixedYReferral, float downAerialVxReferral, float downAerialVyReferral, float downAerialDamageReferral, float downAerialStartUpDurationReferral, float downAerialActiveDurationReferral, float downAerialEndLagDurationReferral, bool downAerialIsAttachedToPlayerReferral, bool downAerialDissapearOnHitReferral, int forwardSpecialAdditionalXReferral, int forwardSpecialAdditionalYReferral, int forwardSpecialWidthReferral, int forwardSpecialHeightReferral, float forwardSpecialStunDurationReferral, float forwardSpecialScalarXReferral, float forwardSpecialScalarYReferral, float forwardSpecialFixedXReferral, float forwardSpecialFixedYReferral, float forwardSpecialVxReferral, float forwardSpecialVyReferral, float forwardSpecialDamageReferral, float forwardSpecialStartUpDurationReferral, float forwardSpecialActiveDurationReferral, float forwardSpecialEndLagDurationReferral, bool forwardSpecialIsAttachedToPlayerReferral, bool forwardSpecialDissapearOnHitReferral, int upSpecialAdditionalXReferral, int upSpecialAdditionalYReferral, int upSpecialWidthReferral, int upSpecialHeightReferral, float upSpecialStunDurationReferral, float upSpecialScalarXReferral, float upSpecialScalarYReferral, float upSpecialFixedXReferral, float upSpecialFixedYReferral, float upSpecialVxReferral, float upSpecialVyReferral, float upSpecialDamageReferral, float upSpecialStartUpDurationReferral, float upSpecialActiveDurationReferral, float upSpecialEndLagDurationReferral, bool upSpecialIsAttachedToPlayerReferral, bool upSpecialDissapearOnHitReferral, int downSpecialAdditionalXReferral, int downSpecialAdditionalYReferral, int downSpecialWidthReferral, int downSpecialHeightReferral, float downSpecialStunDurationReferral, float downSpecialScalarXReferral, float downSpecialScalarYReferral, float downSpecialFixedXReferral, float downSpecialFixedYReferral, float downSpecialVxReferral, float downSpecialVyReferral, float downSpecialDamageReferral, float downSpecialStartUpDurationReferral, float downSpecialActiveDurationReferral, float downSpecialEndLagDurationReferral, bool downSpecialIsAttachedToPlayerReferral, bool downSpecialDissapearOnHit);
	void IsHit(int stunReferral, int damage, int fixedX, int fixedY, int scalarX, int scalarY);
	int lives = 3;
	float x = 800;
	float y = 0;
	int width = 100;
	int height = 100;
	int moveDuration = 0;
	int playerPercentage = 0;
	int stun = 0;
	bool facingRight = true;
private:
	float vx = 0;
	float vy = 0;
	float speed = 0;
	float walkSpeed = 0;
	float aerialSpeed = 0;
	float acceleration = 0;
	float walkAcceleration = 0;
	float aerialAcceleration = 0;
	float groundJumpHeight = 0;
	float aerialJumpHeight = 0;
	float fallAcceleration = 0;
	float fallSpeed = 0;
	float weight = 0;
	int doubleJump = 0;
	int maxDoubleJump = 0;
	int moveThatHit = 0;
	bool onStage = false;
	bool jumpKeyHeld = false;
	bool fastFalling = false;
	Move Move1, Move2, Move3, Move4, Move5;

	int forwardLightAdditionalX = 0;
	int forwardLightAdditionalY = 0;
	int forwardLightWidth = 0;
	int forwardLightHeight = 0;
	float forwardLightStunDuration = 0;
	float forwardLightScalarX = 0;
	float forwardLightScalarY = 0;
	float forwardLightFixedX = 0;
	float forwardLightFixedY = 0;
	float forwardLightVx = 0;
	float forwardLightVy = 0;
	float forwardLightDamage = 0;
	float forwardLightStartUpDuration = 0;
	float forwardLightActiveDuration = 0;
	float forwardLightEndLagDuration = 0;
	bool forwardLightIsAttachedToPlayer = false;
	bool forwardLightDissapearOnHit = false;

	int upLightAdditionalX = 0;
	int upLightAdditionalY = 0;
	int upLightWidth = 0;
	int upLightHeight = 0;
	float upLightStunDuration = 0;
	float upLightScalarX = 0;
	float upLightScalarY = 0;
	float upLightFixedX = 0;
	float upLightFixedY = 0;
	float upLightVx = 0;
	float upLightVy = 0;
	float upLightDamage = 0;
	float upLightStartUpDuration = 0;
	float upLightActiveDuration = 0;
	float upLightEndLagDuration = 0;
	bool upLightIsAttachedToPlayer = false;
	bool upLightDissapearOnHit = false;

	int downLightAdditionalX = 0;
	int downLightAdditionalY = 0;
	int downLightWidth = 0;
	int downLightHeight = 0;
	float downLightStunDuration = 0;
	float downLightScalarX = 0;
	float downLightScalarY = 0;
	float downLightFixedX = 0;
	float downLightFixedY = 0;
	float downLightVx = 0;
	float downLightVy = 0;
	float downLightDamage = 0;
	float downLightStartUpDuration = 0;
	float downLightActiveDuration = 0;
	float downLightEndLagDuration = 0;
	bool downLightIsAttachedToPlayer = false;
	bool downLightDissapearOnHit = false;

	int forwardHeavyAdditionalX = 0;
	int forwardHeavyAdditionalY = 0;
	int forwardHeavyWidth = 0;
	int forwardHeavyHeight = 0;
	float forwardHeavyStunDuration = 0;
	float forwardHeavyScalarX = 0;
	float forwardHeavyScalarY = 0;
	float forwardHeavyFixedX = 0;
	float forwardHeavyFixedY = 0;
	float forwardHeavyVx = 0;
	float forwardHeavyVy = 0;
	float forwardHeavyDamage = 0;
	float forwardHeavyStartUpDuration = 0;
	float forwardHeavyActiveDuration = 0;
	float forwardHeavyEndLagDuration = 0;
	bool forwardHeavyIsAttachedToPlayer = false;
	bool forwardHeavyDissapearOnHit = false;

	int upHeavyAdditionalX = 0;
	int upHeavyAdditionalY = 0;
	int upHeavyWidth = 0;
	int upHeavyHeight = 0;
	float upHeavyStunDuration = 0;
	float upHeavyScalarX = 0;
	float upHeavyScalarY = 0;
	float upHeavyFixedX = 0;
	float upHeavyFixedY = 0;
	float upHeavyVx = 0;
	float upHeavyVy = 0;
	float upHeavyDamage = 0;
	float upHeavyStartUpDuration = 0;
	float upHeavyActiveDuration = 0;
	float upHeavyEndLagDuration = 0;
	bool upHeavyIsAttachedToPlayer = false;
	bool upHeavyDissapearOnHit = false;

	int downHeavyAdditionalX = 0;
	int downHeavyAdditionalY = 0;
	int downHeavyWidth = 0;
	int downHeavyHeight = 0;
	float downHeavyStunDuration = 0;
	float downHeavyScalarX = 0;
	float downHeavyScalarY = 0;
	float downHeavyFixedX = 0;
	float downHeavyFixedY = 0;
	float downHeavyVx = 0;
	float downHeavyVy = 0;
	float downHeavyDamage = 0;
	float downHeavyStartUpDuration = 0;
	float downHeavyActiveDuration = 0;
	float downHeavyEndLagDuration = 0;
	bool downHeavyIsAttachedToPlayer = false;
	bool downHeavyDissapearOnHit = false;

	int forwardAerialAdditionalX = 0;
	int forwardAerialAdditionalY = 0;
	int forwardAerialWidth = 0;
	int forwardAerialHeight = 0;
	float forwardAerialStunDuration = 0;
	float forwardAerialScalarX = 0;
	float forwardAerialScalarY = 0;
	float forwardAerialFixedX = 0;
	float forwardAerialFixedY = 0;
	float forwardAerialVx = 0;
	float forwardAerialVy = 0;
	float forwardAerialDamage = 0;
	float forwardAerialStartUpDuration = 0;
	float forwardAerialActiveDuration = 0;
	float forwardAerialEndLagDuration = 0;
	bool forwardAerialIsAttachedToPlayer = false;
	bool forwardAerialDissapearOnHit = false;

	int backAerialAdditionalX = 0;
	int backAerialAdditionalY = 0;
	int backAerialWidth = 0;
	int backAerialHeight = 0;
	float backAerialStunDuration = 0;
	float backAerialScalarX = 0;
	float backAerialScalarY = 0;
	float backAerialFixedX = 0;
	float backAerialFixedY = 0;
	float backAerialVx = 0;
	float backAerialVy = 0;
	float backAerialDamage = 0;
	float backAerialStartUpDuration = 0;
	float backAerialActiveDuration = 0;
	float backAerialEndLagDuration = 0;
	bool backAerialIsAttachedToPlayer = false;
	bool backAerialDissapearOnHit = false;

	int upAerialAdditionalX = 0;
	int upAerialAdditionalY = 0;
	int upAerialWidth = 0;
	int upAerialHeight = 0;
	float upAerialStunDuration = 0;
	float upAerialScalarX = 0;
	float upAerialScalarY = 0;
	float upAerialFixedX = 0;
	float upAerialFixedY = 0;
	float upAerialVx = 0;
	float upAerialVy = 0;
	float upAerialDamage = 0;
	float upAerialStartUpDuration = 0;
	float upAerialActiveDuration = 0;
	float upAerialEndLagDuration = 0;
	bool upAerialIsAttachedToPlayer = false;
	bool upAerialDissapearOnHit = false;

	int downAerialAdditionalX = 0;
	int downAerialAdditionalY = 0;
	int downAerialWidth = 0;
	int downAerialHeight = 0;
	float downAerialStunDuration = 0;
	float downAerialScalarX = 0;
	float downAerialScalarY = 0;
	float downAerialFixedX = 0;
	float downAerialFixedY = 0;
	float downAerialVx = 0;
	float downAerialVy = 0;
	float downAerialDamage = 0;
	float downAerialStartUpDuration = 0;
	float downAerialActiveDuration = 0;
	float downAerialEndLagDuration = 0;
	bool downAerialIsAttachedToPlayer = false;
	bool downAerialDissapearOnHit = false;

	int forwardSpecialAdditionalX = 0;
	int forwardSpecialAdditionalY = 0;
	int forwardSpecialWidth = 0;
	int forwardSpecialHeight = 0;
	float forwardSpecialStunDuration = 0;
	float forwardSpecialScalarX = 0;
	float forwardSpecialScalarY = 0;
	float forwardSpecialFixedX = 0;
	float forwardSpecialFixedY = 0;
	float forwardSpecialVx = 0;
	float forwardSpecialVy = 0;
	float forwardSpecialDamage = 0;
	float forwardSpecialStartUpDuration = 0;
	float forwardSpecialActiveDuration = 0;
	float forwardSpecialEndLagDuration = 0;
	bool forwardSpecialIsAttachedToPlayer = false;
	bool forwardSpecialDissapearOnHit = false;

	int upSpecialAdditionalX = 0;
	int upSpecialAdditionalY = 0;
	int upSpecialWidth = 0;
	int upSpecialHeight = 0;
	float upSpecialStunDuration = 0;
	float upSpecialScalarX = 0;
	float upSpecialScalarY = 0;
	float upSpecialFixedX = 0;
	float upSpecialFixedY = 0;
	float upSpecialVx = 0;
	float upSpecialVy = 0;
	float upSpecialDamage = 0;
	float upSpecialStartUpDuration = 0;
	float upSpecialActiveDuration = 0;
	float upSpecialEndLagDuration = 0;
	bool upSpecialIsAttachedToPlayer = false;
	bool upSpecialDissapearOnHit = false;

	int downSpecialAdditionalX = 0;
	int downSpecialAdditionalY = 0;
	int downSpecialWidth = 0;
	int downSpecialHeight = 0;
	float downSpecialStunDuration = 0;
	float downSpecialScalarX = 0;
	float downSpecialScalarY = 0;
	float downSpecialFixedX = 0;
	float downSpecialFixedY = 0;
	float downSpecialVx = 0;
	float downSpecialVy = 0;
	float downSpecialDamage = 0;
	float downSpecialStartUpDuration = 0;
	float downSpecialActiveDuration = 0;
	float downSpecialEndLagDuration = 0;
	bool downSpecialIsAttachedToPlayer = false;
	bool downSpecialDissapearOnHit = false;
};